### PR TITLE
Form bugs

### LINKED ISSUE #46: Creating Tasks
1. Can't create a task for the first member in the dropdown options. It give them a task, we have to select another member and then go back to select the first member. 

2. You cannot change the state of a task in the create form

### PR DESCRIPTION
**Pull request by ashleyann9535**
Fixed the convert date warning error for the create form vs the update form

Fixed the state of task in create bug. In the create task, the given state appears and passes validation but now if you want to change the state that works too. The update task is still working as well.

### CODE REVIEW

File: client/src/components/Form.js [hunk 1]
```diff
@@ -189,11 +191,9 @@ const Form = (props) => {
                 name="state"
                 type="text"
                 className="form-select"
-                value={
-                  buttonText === "Save & Close" ?
-                  task.state = buttonState :
-                  task.state
-                }
+                value={buttonText === "Save & Close" ?
+                task.state = task.state || buttonState :
```
Comment (edfenton) [inline client/src/components/Form.js:195]: This is genius!

**Comment by edfenton** [comment]
Bugs squashed!
